//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_overworld_tiles_H
#define METASPRITE_overworld_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define overworld_tiles_TILE_ORIGIN 144
#define overworld_tiles_TILE_W 8
#define overworld_tiles_TILE_H 8
#define overworld_tiles_WIDTH 256
#define overworld_tiles_HEIGHT 256
#define overworld_tiles_TILE_COUNT 223
#define overworld_tiles_PALETTE_COUNT 4
#define overworld_tiles_COLORS_PER_PALETTE 4
#define overworld_tiles_TOTAL_COLORS 16

BANKREF_EXTERN(overworld_tiles)

extern const palette_color_t overworld_tiles_palettes[16];
extern const uint8_t overworld_tiles_tiles[3568];

#endif
