//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_388_H
#define METASPRITE_bg_overworld_388_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_388_TILE_ORIGIN 0
#define bg_overworld_388_TILE_W 8
#define bg_overworld_388_TILE_H 8
#define bg_overworld_388_WIDTH 128
#define bg_overworld_388_HEIGHT 128
#define bg_overworld_388_TILE_COUNT 0
#define bg_overworld_388_PALETTE_COUNT 5
#define bg_overworld_388_COLORS_PER_PALETTE 4
#define bg_overworld_388_TOTAL_COLORS 20
#define bg_overworld_388_MAP_ATTRIBUTES bg_overworld_388_map_attributes
#define bg_overworld_388_MAP_ATTRIBUTES_WIDTH 16
#define bg_overworld_388_MAP_ATTRIBUTES_HEIGHT 16
#define bg_overworld_388_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_overworld_388_MAP_ATTRIBUTES_PACKED_HEIGHT 16
extern const unsigned char bg_overworld_388_map[256];
extern const unsigned char bg_overworld_388_map_attributes[256];

BANKREF_EXTERN(bg_overworld_388)


#endif
