//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_791_H
#define METASPRITE_bg_overworld_791_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_791_TILE_ORIGIN 0
#define bg_overworld_791_TILE_W 8
#define bg_overworld_791_TILE_H 8
#define bg_overworld_791_WIDTH 128
#define bg_overworld_791_HEIGHT 128
#define bg_overworld_791_TILE_COUNT 0
#define bg_overworld_791_PALETTE_COUNT 5
#define bg_overworld_791_COLORS_PER_PALETTE 4
#define bg_overworld_791_TOTAL_COLORS 20
#define bg_overworld_791_MAP_ATTRIBUTES bg_overworld_791_map_attributes
#define bg_overworld_791_MAP_ATTRIBUTES_WIDTH 16
#define bg_overworld_791_MAP_ATTRIBUTES_HEIGHT 16
#define bg_overworld_791_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_overworld_791_MAP_ATTRIBUTES_PACKED_HEIGHT 16
extern const unsigned char bg_overworld_791_map[256];
extern const unsigned char bg_overworld_791_map_attributes[256];

BANKREF_EXTERN(bg_overworld_791)


#endif
