//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_124_H
#define METASPRITE_bg_overworld_124_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_124_TILE_ORIGIN 0
#define bg_overworld_124_TILE_W 8
#define bg_overworld_124_TILE_H 8
#define bg_overworld_124_WIDTH 256
#define bg_overworld_124_HEIGHT 256
#define bg_overworld_124_TILE_COUNT 0
#define bg_overworld_124_PALETTE_COUNT 5
#define bg_overworld_124_COLORS_PER_PALETTE 4
#define bg_overworld_124_TOTAL_COLORS 20
#define bg_overworld_124_MAP_ATTRIBUTES bg_overworld_124_map_attributes
#define bg_overworld_124_MAP_ATTRIBUTES_WIDTH 32
#define bg_overworld_124_MAP_ATTRIBUTES_HEIGHT 32
#define bg_overworld_124_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define bg_overworld_124_MAP_ATTRIBUTES_PACKED_HEIGHT 32
extern const unsigned char bg_overworld_124_map[1024];
extern const unsigned char bg_overworld_124_map_attributes[1024];

BANKREF_EXTERN(bg_overworld_124)


#endif
