//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_79_H
#define METASPRITE_bg_overworld_79_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_79_TILE_ORIGIN 0
#define bg_overworld_79_TILE_W 8
#define bg_overworld_79_TILE_H 8
#define bg_overworld_79_WIDTH 256
#define bg_overworld_79_HEIGHT 256
#define bg_overworld_79_TILE_COUNT 0
#define bg_overworld_79_PALETTE_COUNT 5
#define bg_overworld_79_COLORS_PER_PALETTE 4
#define bg_overworld_79_TOTAL_COLORS 20
#define bg_overworld_79_MAP_ATTRIBUTES bg_overworld_79_map_attributes
#define bg_overworld_79_MAP_ATTRIBUTES_WIDTH 32
#define bg_overworld_79_MAP_ATTRIBUTES_HEIGHT 32
#define bg_overworld_79_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define bg_overworld_79_MAP_ATTRIBUTES_PACKED_HEIGHT 32
extern const unsigned char bg_overworld_79_map[1024];
extern const unsigned char bg_overworld_79_map_attributes[1024];

BANKREF_EXTERN(bg_overworld_79)


#endif
