//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_1022_H
#define METASPRITE_bg_overworld_1022_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_1022_TILE_ORIGIN 0
#define bg_overworld_1022_TILE_W 8
#define bg_overworld_1022_TILE_H 8
#define bg_overworld_1022_WIDTH 128
#define bg_overworld_1022_HEIGHT 128
#define bg_overworld_1022_TILE_COUNT 0
#define bg_overworld_1022_PALETTE_COUNT 5
#define bg_overworld_1022_COLORS_PER_PALETTE 4
#define bg_overworld_1022_TOTAL_COLORS 20
#define bg_overworld_1022_MAP_ATTRIBUTES bg_overworld_1022_map_attributes
#define bg_overworld_1022_MAP_ATTRIBUTES_WIDTH 16
#define bg_overworld_1022_MAP_ATTRIBUTES_HEIGHT 16
#define bg_overworld_1022_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_overworld_1022_MAP_ATTRIBUTES_PACKED_HEIGHT 16
extern const unsigned char bg_overworld_1022_map[256];
extern const unsigned char bg_overworld_1022_map_attributes[256];

BANKREF_EXTERN(bg_overworld_1022)


#endif
