//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_211_H
#define METASPRITE_bg_overworld_211_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_211_TILE_ORIGIN 0
#define bg_overworld_211_TILE_W 8
#define bg_overworld_211_TILE_H 8
#define bg_overworld_211_WIDTH 256
#define bg_overworld_211_HEIGHT 256
#define bg_overworld_211_TILE_COUNT 0
#define bg_overworld_211_PALETTE_COUNT 5
#define bg_overworld_211_COLORS_PER_PALETTE 4
#define bg_overworld_211_TOTAL_COLORS 20
#define bg_overworld_211_MAP_ATTRIBUTES bg_overworld_211_map_attributes
#define bg_overworld_211_MAP_ATTRIBUTES_WIDTH 32
#define bg_overworld_211_MAP_ATTRIBUTES_HEIGHT 32
#define bg_overworld_211_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define bg_overworld_211_MAP_ATTRIBUTES_PACKED_HEIGHT 32
extern const unsigned char bg_overworld_211_map[1024];
extern const unsigned char bg_overworld_211_map_attributes[1024];

BANKREF_EXTERN(bg_overworld_211)


#endif
