//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_overworld_321_H
#define METASPRITE_bg_overworld_321_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_overworld_321_TILE_ORIGIN 0
#define bg_overworld_321_TILE_W 8
#define bg_overworld_321_TILE_H 8
#define bg_overworld_321_WIDTH 128
#define bg_overworld_321_HEIGHT 128
#define bg_overworld_321_TILE_COUNT 0
#define bg_overworld_321_PALETTE_COUNT 5
#define bg_overworld_321_COLORS_PER_PALETTE 4
#define bg_overworld_321_TOTAL_COLORS 20
#define bg_overworld_321_MAP_ATTRIBUTES bg_overworld_321_map_attributes
#define bg_overworld_321_MAP_ATTRIBUTES_WIDTH 16
#define bg_overworld_321_MAP_ATTRIBUTES_HEIGHT 16
#define bg_overworld_321_MAP_ATTRIBUTES_PACKED_WIDTH 16
#define bg_overworld_321_MAP_ATTRIBUTES_PACKED_HEIGHT 16
extern const unsigned char bg_overworld_321_map[256];
extern const unsigned char bg_overworld_321_map_attributes[256];

BANKREF_EXTERN(bg_overworld_321)


#endif
